### ISSUE TITLE
DeviceOrientation.portraitUp?????? Right?????

### ISSUE THREAD

**Issue by bakboem** [RafaelBarbosatec/qr_code_dart_scan#30]

**Comment by RafaelBarbosatec** [comment]
Yes

**Comment by bakboem** [comment]
bro, I used a decoder only.  because the camera  Orientation is naughty.

**Comment by RafaelBarbosatec** [comment]
Hi @bakboem .
I don't understood your point.
What do you need?
Do you have some problem with the camera?
Do you have any suggestions?

**Comment by bakboem** [comment]
> Hi @bakboem . I don't understood your point. What do you need? Do you have some problem with the camera? Do you have any suggestions?

Yes, the camera calls in your plugin are insufficient, I think you should only support portrait orientation

**Comment by T1G3R192** [comment]
@RafaelBarbosatec there is indeed a problem, whenever you need the camera to open in the orientation `portraitUp`. You need to set it to landscapeRight like this:  `lockCaptureOrientation: DeviceOrientation.landscapeRight,` in order to achieve the desired result. The camera is always opened with a 90 degrees tilt toward the left side of the device.

**Comment by bakboem** [comment]
> @RafaelBarbosatec确实存在一个问题，每当您需要以 方向打开相机时`portraitUp`。您需要将其设置为横向右，如下所示： `lockCaptureOrientation: DeviceOrientation.landscapeRight,`才能获得所需的结果。相机始终以 90 度倾斜朝向设备左侧的方式打开。
Yes, you are right. 
The camera's sensor orientation is inconsistent with the screen orientation (most rear camera sensors are actually "horizontally", sensorOrientation=90 or 270, resulting in the output data being naturally horizontal). If the underlying camera2 api is used, the direction should be recalculated
```
val relativeRotation = (sensorOrientation - deviceOrientation + 360) % 360
MediaMuxer.setOrientationHint(relativeRotation)
```

**Comment by bakboem** [comment]
> @RafaelBarbosatec there is indeed a problem, whenever you need the camera to open in the orientation `portraitUp`. You need to set it to landscapeRight like this: `lockCaptureOrientation: DeviceOrientation.landscapeRight,` in order to achieve the desired result. The camera is always opened with a 90 degrees tilt toward the left side of the device.

Yes, you are right. The camera's sensor orientation is inconsistent with the screen orientation (most rear camera sensors are actually "horizontally", sensorOrientation=90 or 270, resulting in the output data being naturally horizontal). If the underlying camera2 api is used, the direction should be recalculated
```
val relativeRotation = (sensorOrientation - deviceOrientation + 360) % 360
MediaMuxer.setOrientationHint(relativeRotation)
```

**Comment by RafaelBarbosatec** [comment]
Hi @bakboem !
In the version `0.9.5` there is a param `forceReadPortrait`. if true force read portrait. useful to read EAN-13 and EAN-8 without rotate device.

I hope that it help you.

**Comment by RafaelBarbosatec** [comment]
Fixed in current version.
Now read image portrait by default. If you need read image landscape just set forceReadLandscape = true.

**Comment by T1G3R192** [comment]
@RafaelBarbosatec unfortunately, for me it is not fixed! See my comment above...

 qr_code_dart_scan: ^0.9.8
 
 forceReadLandscape: true, // has no effect
 lockCaptureOrientation: DeviceOrientation.landscapeRight, // is still required

**Comment by RafaelBarbosatec** [comment]
Hi @T1G3R192 . Your app was rotating?
You need keep portrait the app.
Keep the lockCaptureOrientation default

**Comment by T1G3R192** [comment]
@RafaelBarbosatec Yes, as previously mentioned, the emulated camera on android is always always opened with a 90 degrees tilt towards the left side of the device, whenever I keep the lockCaptureOrientation on default.
FYI: I even locked the devices accepted orientation with SystemChrome like this, but it has no effect on the camera. As you can see, my scanner overlay is rendered correctly.

```
SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((fn) {
    runApp(
```

Emulator:

![Image](https://github.com/user-attachments/assets/b5316dc9-8660-4db5-a36f-ab9e07afaf2a)


This is my code:
```
 QRCodeDartScanView(
          controller: _controller,
          scanInvertedQRCode: false,
          formats: const [BarcodeFormat.qrCode],
          typeCamera: TypeCamera.back,
          // forceReadLandscape: true,
          // lockCaptureOrientation: DeviceOrientation.landscapeRight,
          typeScan: TypeScan.live,
          intervalScan: const Duration(seconds: 1),
          onCapture: (Result result) {
```

**Comment by RafaelBarbosatec** [comment]
Very strange. I use this package in some apps with millions of users and don't have this problem.
In real device do you have the same problem?

Which flutter version are you using?

**Comment by bakboem** [comment]
> Hi [@bakboem](https://github.com/bakboem) ! In the version `0.9.5` there is a param `forceReadPortrait`. if true force read portrait. useful to read EAN-13 and EAN-8 without rotate device.
> 
> I hope that it help you.

Very good improvement. I only used your decoder before. It seems that I can use all your functions with confidence.

`
Result? currentResult;
  CameraController? cameraController;
  QRCodeDartScanDecoder decoder = QRCodeDartScanDecoder(formats: [BarcodeFormat.qrCode]);
  StreamSubscription<scanner.ScanResult>? _subscription;
`
